[tasks.build-rust-api]
script = ['''
cd crates/navara_wasm_api
wasm-pack build --release --target web --out-dir ../../web/wasm/navara_engine_api
''']

[tasks.build-dev-rust-api]
script = ['''
cd crates/navara_wasm_api
wasm-pack build --dev --target web --out-dir ../../web/wasm/navara_engine_api
''']

[tasks.watch-rust-api]
script = ['''
cd crates/navara_wasm_api
cargo watch -i .gitignore -i "pkg/*" -s "wasm-pack build --dev --target web && cp -r ./pkg/** ../../web/wasm/navara_engine_api" --poll
''']

[tasks.watch-rust-api.windows]
script = ['''
cd crates/navara_wasm_api
cargo watch -i .gitignore -i "pkg/*" -s "wasm-pack build --dev --target web && robocopy .\\pkg\\ ..\\..\\web\\wasm\\navara_engine_api /Mir > nul" --poll
''']

[tasks.watch-release-rust-api]
script = ['''
cd crates/navara_wasm_api
cargo watch -i .gitignore -i "pkg/*" -s "wasm-pack build --release --target web && cp -r ./pkg/** ../../web/wasm/navara_engine_api" --poll
''']

[tasks.watch-release-rust-api.windows]
script = ['''
cd crates/navara_wasm_api
cargo watch -i .gitignore -i "pkg/*" -s "wasm-pack build --release --target web && robocopy .\\pkg\\ ..\\..\\web\\wasm\\navara_engine_api /Mir > nul" --poll
''']
