# ============================================================================
#                               BUILD TASKS
# ============================================================================
# Generate JS bindings for worker WASM module
[tasks.bindgen-rust-worker]
script = ['''
#!/usr/bin/env bash

wasm-bindgen target/wasm32-unknown-unknown/release/navara_wasm_worker.wasm --out-dir web/wasm/navara_engine_worker --target web
if command -v wasm-opt &> /dev/null; then
    wasm-opt -O4 web/wasm/navara_engine_worker/navara_wasm_worker_bg.wasm -o web/wasm/navara_engine_worker/navara_wasm_worker_bg.wasm
  else
    echo "wasm-opt not found, skipping optimization"
fi

# Generate package.json for pnpm workspace
cp crates/navara_wasm_worker/_package.json web/wasm/navara_engine_worker/package.json
''']

[tasks.bindgen-rust-worker.windows]
script = ['''
wasm-bindgen target/wasm32-unknown-unknown/release/navara_wasm_worker.wasm --out-dir web/wasm/navara_engine_worker --target web
where wasm-opt >nul 2>&1 && wasm-opt -O4 web/wasm/navara_engine_worker/navara_wasm_worker_bg.wasm -o web/wasm/navara_engine_worker/navara_wasm_worker_bg.wasm || echo "wasm-opt not found, skipping optimization"

REM Generate package.json for pnpm workspace
copy /Y "crates\navara_wasm_worker\_package.json" "web\wasm\navara_engine_worker\package.json"
''']

[tasks.bindgen-dev-rust-worker]
script = ['''
#!/usr/bin/env bash

wasm-bindgen target/wasm32-unknown-unknown/debug/navara_wasm_worker.wasm --out-dir web/wasm/navara_engine_worker --target web --keep-debug

# Generate package.json for pnpm workspace
cp crates/navara_wasm_worker/_package.json web/wasm/navara_engine_worker/package.json
''']

[tasks.bindgen-dev-rust-worker.windows]
script = ['''
wasm-bindgen target/wasm32-unknown-unknown/debug/navara_wasm_worker.wasm --out-dir web/wasm/navara_engine_worker --target web --keep-debug

REM Generate package.json for pnpm workspace
copy /Y "crates\navara_wasm_worker\_package.json" "web\wasm\navara_engine_worker\package.json"
''']