[tasks.build-rust-worker]
script = ['''
cd crates/navara_wasm_worker
wasm-pack build --dev --out-dir ../../web/wasm/navara_engine_worker --target web --release
''']

[tasks.build-dev-rust-worker]
script = ['''
cd crates/navara_wasm_worker
wasm-pack build --dev --out-dir ../../web/wasm/navara_engine_worker --target web
''']

[tasks.watch-rust-worker]
script = ['''
cd crates/navara_wasm_worker
cargo watch -i .gitignore -i "pkg/*" -s "wasm-pack build --dev --target web && cp -r ./pkg/** ../../web/wasm/navara_engine_worker" --poll
''']

[tasks.watch-rust-worker.windows]
script = ['''
cd crates/navara_wasm_worker
cargo watch -i .gitignore -i "pkg/*" -s "wasm-pack build --dev --target web && robocopy .\\pkg\\ ..\\..\\web\\wasm\\navara_engine_worker /Mir > nul" --poll
''']
