[tasks.install-deps-web]
script = ['''
pnpm i
''']

[tasks.dev-web]
script = ['''
pnpm dev
''']
dependencies = ["install-deps-web"]

[tasks.build-web-example]
script = ['''
pnpm build:example
''']
dependencies = ["install-deps-web"]

[tasks.build-web]
script = ['''
pnpm build
''']
dependencies = ["install-deps-web"]

[tasks.lint-web]
script = ['''
pnpm lint
''']
dependencies = ["install-deps-web"]

[tasks.lint-check-web]
script = ['''
pnpm lint:check
''']
dependencies = ["install-deps-web"]

[tasks.format-web]
script = ['''
pnpm format
''']
dependencies = ["install-deps-web"]

[tasks.format-check-web]
script = ['''
pnpm format:check
''']
dependencies = ["install-deps-web"]

[tasks.test-web]
script = ['''
pnpm test
''']
dependencies = ["install-deps-web"]
