apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: navara
  namespace: reearth
  annotations:
    github.com/project-slug: maplibre/navara
  links:
  - url: https://github.com/maplibre/navara
    title: GitHub
    icon: github
  tags:
  - typescript
spec:
  type: service
  lifecycle: production
  owner: maplibre/navara
