[config]
skip_core_tasks = true
default_to_workspace = false

[env]
PROJ_NAME = "navara"

[tasks.format-rust]
script = ['''
#!/usr/bin/env bash -eux
cargo fmt --all
''']

[tasks.format-check-rust]
script = ['''
#!/usr/bin/env bash -eux
cargo fmt --all --check
''']

[tasks.lint-rust]
script = ['''
#!/usr/bin/env bash -eux
cargo clippy --workspace --all-targets --all-features -- -D warnings
''']

[tasks.build-rust]
script = ['''
#!/usr/bin/env bash -eux
cd crates/navara_wasm
wasm-pack build --target web --release
''']

[tasks.test-rust]
script = ['''
#!/usr/bin/env bash -eux
cargo test --workspace --all-targets --all-features
''']

[tasks.build-dev]
script = ['''
#!/usr/bin/env bash -eux
cd crates/navara_wasm
wasm-pack build --target web
''']

[tasks.dev]
run_task = { name = ["watch", "dev-web"], parallel = true }

[tasks.test]
run_task = { name = ["test-rust", "test-web"], parallel = true }

[tasks.lint]
run_task = { name = ["lint-rust", "lint-web"], parallel = true }

[tasks.lint-check]
run_task = { name = ["lint-rust", "lint-check-web"], parallel = true }

[tasks.format]
run_task = { name = ["format-rust", "format-web"], parallel = true }

[tasks.format-check]
run_task = { name = ["format-check-rust", "format-check-web"], parallel = true }

[tasks.build-example]
run_task = { name = ["build-rust", "build-web-example"] }

[tasks.build]
run_task = { name = ["build-rust", "build-web"] }

[tasks.watch]
script = ['''
#!/usr/bin/env bash -eux
cd crates/navara_wasm
cargo watch -i .gitignore -i "pkg/*" -s "wasm-pack build --target web" --poll
''']

[tasks.dev-web]
script = ['''
#!/usr/bin/env bash -eux
cd web/navara_three
npm i && npm run dev
''']

[tasks.build-web-example]
script = ['''
#!/usr/bin/env bash -eux
cd web/navara_three
npm i && npm run build:example
''']

[tasks.build-web]
script = ['''
#!/usr/bin/env bash -eux
cd web/navara_three
npm i && npm run build
''']

[tasks.lint-web]
script = ['''
#!/usr/bin/env bash -eux
cd web/navara_three
npm i && npm run lint
''']

[tasks.lint-check-web]
script = ['''
#!/usr/bin/env bash -eux
cd web/navara_three
npm i && npm run lint:check
''']

[tasks.format-web]
script = ['''
#!/usr/bin/env bash -eux
cd web/navara_three
npm i && npm run format
''']

[tasks.format-check-web]
script = ['''
#!/usr/bin/env bash -eux
cd web/navara_three
npm i && npm run format:check
''']

[tasks.test-web]
script = ['''
#!/usr/bin/env bash -eux
cd web/navara_three
npm i && npm run test
''']

[tasks.doc]
script = ['''
#!/usr/bin/env bash -eux
cargo clean --doc
cargo doc --no-deps --all-features
''']

[tasks.coverage]
script = ['''
#!/usr/bin/env bash -eux
rm -rf target/debug/deps/${PROJ_NAME}-*

export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zinstrument-coverage"
export LLVM_PROFILE_FILE="${PROJ_NAME}-%p-%m.profraw"

cargo build --workspace --verbose
cargo test --workspace --verbose

grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o lcov.info
''']

[tasks.check-easy-panic]
script = ['''
#!/usr/bin/env bash -eux
git ls-files |grep -E '.rs$' |(! xargs grep 'unimplemented!')
git ls-files |grep -E '.rs$' |(! xargs grep 'todo!')
''']
