use super::{ConstructPolylineBatchedFeatureParameters, ConstructPolylineBatchedFeatureResult};

pub type DelegatableConstructPolylineBatchedFeatureParameters =
    ConstructPolylineBatchedFeatureParameters;
pub type DelegatableConstructPolylineBatchedFeatureResult = ConstructPolylineBatchedFeatureResult;
