use super::{ConstructPolygonBatchedFeatureParameters, ConstructPolygonBatchedFeatureResult};

pub type DelegatableConstructPolygonBatchedFeatureParameters =
    ConstructPolygonBatchedFeatureParameters;
pub type DelegatableConstructPolygonBatchedFeatureResult = ConstructPolygonBatchedFeatureResult;
