const TOTAL_CONCURRENCY = navigator.hardwareConcurrency - 1 || 1;
export const FEATURE_CONCURRENCY = Math.floor(TOTAL_CONCURRENCY / 3) || 1;
export const MAP_CONCURRENCY = TOTAL_CONCURRENCY - FEATURE_CONCURRENCY || 1;
export const MESH_CONCURRENCY = Math.floor(MAP_CONCURRENCY / 3);
export const WORKER_TASK_CONCURRENCY = MAP_CONCURRENCY - MESH_CONCURRENCY;
