[package]
name = "navara_parser"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
geojson_lib.workspace = true
geozero.workspace = true
geo-types.workspace = true
rustc-hash.workspace = true
navara_cesiumtiles.workspace = true
navara_b3dm.workspace = true
navara_pnts.workspace = true
navara_glb.workspace = true
navara_property.workspace = true
navara_core.workspace = true
navara_math.workspace = true
navara_geometry.workspace = true
pmtiles.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[dev-dependencies]
