name: Tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@1.93.0
        with:
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt

      # Cache Rust build artifacts and dependencies
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-deps"
          cache-on-failure: true
          # Cache cargo-make and wasm-pack binaries
          cache-all-crates: true

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version: '24.14.1'

      - name: Install Tools (wasm-bindgen-cli, cargo-make)
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-bindgen-cli@0.2.114, cargo-make

      - name: Prepare
        run: cargo make prepare-ci

      - name: Run Build Example
        run: pnpm build:example

      - name: Run Build library
        run: pnpm build

      - name: Build Integration Tests
        run: pnpm build:integration

      - name: Run Test
        run: cargo make test
        env:
          RUST_BACKTRACE: 1

      - name: Cargo format
        run: cargo make format-check

      - name: Lint
        run: cargo make lint-check

  rust-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@1.93.0

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-docs"

      - run: cargo test --doc
      - run: cargo doc --all-features --release
